### ISSUE TITLE
Interest in additional device support?

### ISSUE THREAD

**Issue by jessebraham** [atsamd-rs/atsamd#108]
I've been playing with the [ATSAMD11C14A](https://www.microchip.com/wwwproducts/en/ATSAMD11C14) and decided to take a swing at adding HAL support for this device.

https://github.com/jessebraham/atsamd11-rs

I copied the `hal/src/common/` directory verbatim to my project, then modified the `hal/src/samd21` directory to reflect the new `samd11` device. Everything seems to build except the USB module, which I can't get to build in this project either for some reason, so that has been omitted for the time being.

All I've tested on hardware so far is a basic blinky demo I hacked together, but that seems to be working; I plan on doing some further testing.

Any interest in integrating this into the project, or was the goal to stay focused on the `samd21`/`samd51`?

**Comment by sajattack** [comment]
We'd be very happy to support more devices.

**Comment by jessebraham** [comment]
Awesome, I'll get a PR going. Thanks!
