### ISSUE TITLE
Utilizing configure_gclk_divider_and_source and GENA enums its possible for multiple parties to attempt to take the same clock

### ISSUE THREAD

**Issue by jacobrosenthal** [atsamd-rs/atsamd#114]
Discovered in #113 

Its possible for user and or library subsystems to both attempt to take the same clock causing panic. 

We should look at how to have the clock tree hand out gclk 3-11 just like we do for glck0 and gclk1

**Comment by bradleyharden** [comment]
This will no longer be possible with #450.
