### ISSUE TITLE
Trouble compiling usb_serial example for metro_m0

### ISSUE THREAD

**Issue by pragun** [atsamd-rs/atsamd#116]
Hi, I'm a rust beginner so it is very probable that I am doing something silly,  but on 
`pragun@lubuntu-vm:~/rust_experimentation/atsamd/boards/metro_m0$ cargo build --example usb_serial`

I get 

` Compiling atsamd-hal v0.7.4 (/home/pragun/rust_experimentation/atsamd/hal)
error[E0433]: failed to resolve: could not find `usb` in `hal`
 --> examples/usb_serial.rs:9:15
  |
9 | use hal::hal::usb::usb_device::bus::UsbBusWrapper;
  |               ^^^ could not find `usb` in `hal`
`
which of course brings up a host of other compile errors. 

It'd be great if someone could point me down the right path here, thanks!

**Comment by jessebraham** [comment]
It's not just you, unfortunately the HAL for USB isn't in a great state currently. See #11 for more information.

**Comment by pragun** [comment]
Ah thanks!
