### ISSUE TITLE
Version bump for feather_m0 board to enable usb

### ISSUE THREAD

**Issue by TDHolmes** [atsamd-rs/atsamd#200]
I'm using the `feather_m0` board for [a project](https://github.com/TDHolmes/oven-temp-rs) I'm working on, and currently I have to use the git link instead of the version on crates.io since the `usb` feature flag was added after `0.6.0`. Can this be bumped and released?

This is more of a convenience thing, in the meantime I'll just use the direct git link.

**Comment by sajattack** [comment]
Done
