### ISSUE TITLE
Wiki documentation for adding a new chip

### ISSUE THREAD

**Issue by jaredwolff** [atsamd-rs/atsamd#204]
The only thing I would add to this is that Microchip's download site provides files in ".atpack" format. I simply renamed to .zip and it decompressed everything nicely. For some reason my SAMD21J was in the SAMD21C folder. So searching for your target SVD works best. :)

Happy to make these edits myself. Thanks!

**Comment by sajattack** [comment]
Right. Previously we had a bunch of extra svds in the repo but they were removed. I'll make this change.
