### ISSUE TITLE
Would This work with ADAFRUIT FEATHER M0 WIFI - ATSAMD21 + ATWINC1500?

### ISSUE THREAD

**Issue by bobhenkel** [atsamd-rs/atsamd#215]
I'm really new to embedded so keep that in mind. 

Would this be able to make use of this board https://www.adafruit.com/product/3010 and make use of the wifi?

Thanks!

**Comment by sajattack** [comment]
I'm not aware of a rust crate for the ATWINC1500.

**Comment by sajattack** [comment]
@fionawhim is working on wifi support for boards like the pyportal that use esp32 for wifi https://github.com/fionawhim/wifinina

**Comment by fionawhim** [comment]
Yep. Unfortunately the ESP32 WiFiNINA looks to share nothing with the ATWINC1500 besides both being communicated with over SPI. (From the look of it, Adafruit indicates that driving a ATWINC1500 is so complicated that they can’t fit it in Python on an M0?)

My stuff will work with PyPortal and, presumably, anything that Adafruit markets as "AirLift."

**Comment by bobhenkel** [comment]
Thanks for the quick response @sajattack and @fionawhim
