### ISSUE TITLE
Feather M4 has incorrect D0/D1 pins

### ISSUE THREAD

**Issue by fionawhim** [atsamd-rs/atsamd#229]
On the Feather M4, the [pinout](https://learn.adafruit.com/assets/78439) has RX (D0) on PB17 and TX (D1) on PB16.

The `define_pins!` statement in [lib.rs](https://github.com/atsamd-rs/atsamd/blob/master/boards/feather_m4/src/lib.rs) has these two reversed.

**Comment by jessebraham** [comment]
@fionawhim thanks for pointing this out! This problem will be fixed in the next release of the board's crate.
