### ISSUE TITLE
Build error "feature(panic_implementation)" 

### ISSUE THREAD

**Issue by mkotsbak** [atsamd-rs/atsamd#26]
I tried following instructions in Readme, but only get these build errors (Feather M0):

error[E0557]: feature has been removed in #![feature(panic_implementation)] (build-all.sh)

**Comment by wez** [comment]
Our CI is building successfully; can you confirm that you're building with the current master of this repo and that you have the latest nightly rust compiler?  You may need to run `rustup update`

**Comment by mkotsbak** [comment]
I could not reproduce the issue anymore so it seems it is fixed.
