### ISSUE TITLE
Implement RNG abstraction

### ISSUE THREAD

**Issue by BenBergman** [atsamd-rs/atsamd#27]
The embedded-hal crate provides a trait for an RNG but I don't believe it is implemented yet. I haven't had a chance to research it yet but wanted to get the feature tracked.

https://docs.rs/embedded-hal/0.2.2/embedded_hal/blocking/rng/trait.Read.html

**Comment by sajattack** [comment]
I think only the '51 has the rng, not the '21

**Comment by BenBergman** [comment]
Oh, interesting. I guess I need to read the LSB of a floating ADC a few times to get a random number or something... Or is there something generic that we could provide with the hal as a psuedo RNG?

**Comment by sajattack** [comment]
I think circuitpython just uses a software PRNG.

**Comment by sajattack** [comment]
Looks like the best way to do this is implement the RngCore trait. https://docs.rs/rand/0.5.0-pre.0/rand/trait.RngCore.html
