### ISSUE TITLE
atsamd-rs documentation site seems to be down

### ISSUE THREAD

**Issue by TDHolmes** [atsamd-rs/atsamd#287]
The documentation link on atsamd-rs on [crates.io](https://crates.io/crates/atsamd-hal) points to https://atsamd-rs.github.io, which seems to be down.

**Comment by sajattack** [comment]
Yup, these links are old and should be removed for docs.rs links to take over.

**Comment by TDHolmes** [comment]
[atsamd-hal docs.rs](https://docs.rs/crate/atsamd-hal/0.10.0) seems to not build successfully. Will that be fixed first?

**Comment by sajattack** [comment]
The HAL documentation doesn't build without a specific target board.

**Comment by jessebraham** [comment]
The documentation hosted on [docs.rs](https://docs.rs/atsamd-hal/0.10.1/atsamd_hal/) builds now. Since a chip must be specified, the `samd21g` is being used, as was the case with the old documentation.
