### ISSUE TITLE
SVDs are missing DMA trigger source enumerations

### ISSUE THREAD

**Issue by ianrrees** [atsamd-rs/atsamd#321]
The DMAC has a control register (CHCTRLB for SAMD21 at least) where one field is the DMA trigger source, called TRIGSRC.  It seems the SVD files only have the DISABLED=0 enumeration, but there are actually several different sources.

I see there are some patch files to correct the SVD before the PAC is generated; how are the patch files constructed?

**Comment by jessebraham** [comment]
We are currently using [xsltproc](http://xmlsoft.org/XSLT/xsltproc.html) for patching SVDs. We initially tried to use [svdtools](https://github.com/stm32-rs/svdtools) but ran in to some limitations.

We have a script, [update.sh](https://github.com/atsamd-rs/atsamd/blob/master/update.sh), for patching the SVDs and generating the PACs. You can see [here](https://github.com/atsamd-rs/atsamd/blob/master/update.sh#L25) where we apply the patches. Device-specific patch files can be found [in this directory](https://github.com/atsamd-rs/atsamd/tree/master/svd/devices). Patches shared between multiple devices can be found [here](https://github.com/atsamd-rs/atsamd/tree/master/svd/devices/include).

You can try to apply patches and re-generate the PACs locally, then run `cargo doc` to verify the fields have been generated.
