### ISSUE TITLE
Refactor UART implementation

### ISSUE THREAD

**Issue by twitchyliquid64** [atsamd-rs/atsamd#329]
- [ ] Make UART generic over some trait that manages configuration of the baud rate (arithmetic vs fractional)
- [ ] Have methods to enable/disable interrupts & check intflag properly
- [ ] Handle errors properly by reading `intflag.ERR` + `status.*`, clearing them, and discarding bytes as appropriate
- [ ] Make UART parameters (stop bits, parity, polarity) configurable
- [ ] Generated documentation needs work

**Comment by niclashoyer** [comment]
Does this also include switching the number of data bits? I have a strange requirement where I need 9 data bits, no parity and one stop bit. While the SERCOM on some chips allow such a configuration, it is very uncommon and I feared that it will cause a lot of work down here.

**Comment by TDHolmes** [comment]
That seems like a reasonable extension of "Make UART parameters configurable" to me
