### ISSUE TITLE
Regression in behaviour of 4-bit dither register access for TCC on SAMD51J/G

### ISSUE THREAD

**Issue by proman21** [atsamd-rs/atsamd#377]
I opened issue #88 with the original bug in the register access implementation. I've noticed this behavior has regressed in version 0.9.0 of the `atsamd51j` and `atsamd51g` PAC crates.

**Comment by sajattack** [comment]
Looks like this was back when I was hand-editing the SVDs, and we need a patch for it.

**Comment by twitchyliquid64** [comment]
Ooof, does this need a patch before the next release?

**Comment by TDHolmes** [comment]
I believe I've made the proper fix, please check out the PR and test it out if you can @proman21
