### ISSUE TITLE
ADC Frequency Parameter

### ISSUE THREAD

**Issue by kdsch** [atsamd-rs/atsamd#395]
I'm working on a SAMD51 project involving audio recording, so I need control over the sample rate, which the current HAL does not offer. The PWM HAL does offer control over frequency, and for the sake of consistency I wonder if a similar interface could be useful with the ADC HAL.

The PWM interface exposes two parameters that allow the user to control frequency: a frequency parameter and a clock frequency. `TimerParams` is used to transform these into values for the timer peripheral that indirectly control the PWM frequency.

Likewise, a new ADC HAL could expose similar parameters and perform a similar transformation internally to derive values that indirectly control the ADC frequency. The sample rate is affected by the following things ([45.6.2.8](http://ww1.microchip.com/downloads/en/DeviceDoc/60001507E.pdf#unique_5042)):

- Input clock frequency
- Sampling duration
- Offset compensation
- Resolution (8, 10, or 12 bits)
- Prescaler

I expect that coarse-grained of control over sampling frequency can be attained with these parameters; I assume that applications requiring precise frequencies for compatibility with external formats would use an external codec chip. The PWM is capable of generating more exact frequencies because it uses a high-resolution counter, whereas the ADC's prescaler is pretty coarse-grained. Getting the most precision would require taking all the other parameters into consideration (and note that the input clock frequency can sometimes be controlled by a divider).

In any case, I hope we can get close to typical audio sample rates such as 48kHz and less. Perhaps due to precision issues, mimicking the PWM approach is a poor fit, and we should require users to do the calculations themselves, exposing lower-level parameters.

I am new to Rust and embedded Rust, but I'm interested in contributing this enhancement if we can develop a consensus about it.

**Comment by twitchyliquid64** [comment]
Hi and welcome!

We are always open to PRs and ideas. It would not be controversial to add code to configure the sampling rate et al. to the ADC HAL code.

If you have other ideas you are interested in contributing please share! A bunch of us hang out in the matrix chatroom and are always open to bounce ideas off :)
