### ISSUE TITLE
How to setup periodical timer interrupt on SeeedStudio Xiao(SAMD21)?

### ISSUE THREAD

**Issue by windoze** [atsamd-rs/atsamd#399]
I've tried following code but it doesn't seem to be working:
```
        let mut peripherals = Peripherals::take().unwrap();
        let mut clk_controller = GenericClockController::with_external_32kosc(
            peripherals.GCLK,
            &mut peripherals.PM,
            &mut peripherals.SYSCTRL,
            &mut peripherals.NVMCTRL,
        );
        let clock =clk_controller.gclk1();
        let tc2tc3clock = clk_controller.tcc2_tc3(&clock).unwrap();
        let mut t = TimerCounter::<TC3>::tc3_(&tc2tc3clock, peripherals.TC3, &mut peripherals.PM);
        t.enable_interrupt();
```
Am I doing anything wrong?

**Comment by TDHolmes** [comment]
You are not starting the timer. Check out the `sleeping_timer` examples for some usages. 

You can also call `start` directly to kick off a count down timer, and then in the interrupt handler you can kick it back off by calling `start` again.

**Comment by TDHolmes** [comment]
@windoze , any success?

**Comment by bradleyharden** [comment]
@windoze, I'm going to close this. Please feel free to reopen if you have any more questions.

**Comment by windoze** [comment]
Sorry for the late response.
I tried and it works, thanks!
