### ISSUE TITLE
Wio Terminal wifi examples broke

### ISSUE THREAD

**Issue by imheresamir** [atsamd-rs/atsamd#421]
Hi,

The 2.1.2 wifi chip firmware changed the erpc uart baudrate from 1843200 to 614400: Seeed-Studio/seeed-ambd-firmware#14

Not sure about the reasoning behind the change. PR incoming for the constant update.

Samir

**Comment by twitchyliquid64** [comment]
Thanks!

Can we make a feature flag to switch this? I imagine some people will have older versions of the firmware.

Okay with defaulting to the new value.

**Comment by imheresamir** [comment]
Yup, updated PR. Let me know if you have a better name for the feature than `wifi-fw-before-212`
