### ISSUE TITLE
API cleanup

### ISSUE THREAD

**Issue by glaeqen** [atsamd-rs/atsamd#426]
Effort to standardize API across HAL & BSCs. 

- Remove chip-specific modules
  PR #424 :heavy_check_mark: merged
- Flatten HAL by removing redundant `common` module
  PR #425 :heavy_check_mark: merged
- Update the BSPs to re-export the HAL itself, rather than modules within the HAL (open discussion)
  PR #357 :x: under investigation
- Make the `thumb` modules private, to indicate that they are an implementation detail; consider the remaining modules public and let them become the official API
  PR XXX
- Rename imports across the HAL and the BSPs to increase consistency and clarity. (open discussion)
  PR XXX

**Comment by vccggorski** [comment]
As far as I could see, discussion sorta started already in #357. Nonetheless, properly tracked issue seems more appropriate for such thing.

**Comment by bradleyharden** [comment]
Here's another proposed change. I would like to change `target_device` to `pac`. At the very least, maybe we could support both. Thoughts?

**Comment by Sympatron** [comment]
Maybe we could review the `unproven` feature. Last time I looked a lot of basic stuff was "unproven" (I think because the traits were unproven in `embedded-hal`).

**Comment by Sympatron** [comment]
> Here's another proposed change. I would like to change `target_device` to `pac`. At the very least, maybe we could support both. Thoughts?

Seems like this is already part of PR #357.

**Comment by bradleyharden** [comment]
I meant at the HAL level, not the BSP level. I don't think that PR affects the HAL name.

**Comment by bradleyharden** [comment]
@Sympatron, I would expect unproven to disappear with embedded-hal 1.0, but who knows when that will be.

**Comment by Sympatron** [comment]
Thinking about the `unproven` thing more, I came to the conclusion that we probably should not mark whole modules as "unproven" just because they implement some unproven trait. Everything else in these modules is "proven" (to the same degree as most of the hal). So I would vote to mark only the e-h trait impls as `unproven`.

**Comment by TDHolmes** [comment]
#491

**Comment by TDHolmes** [comment]
> Rename imports across the HAL and the BSPs to increase consistency and clarity. (open discussion)
PR XXX

done in #491

**Comment by ianrrees** [comment]
It seems like the work discussed here has all been done, any reason not to close this?

**Comment by glaeqen** [comment]
I think this issue got outdated considering that I stopped following up on the changes that happened in the meantime. We can close it.
