### ISSUE TITLE
OTA功能

### ISSUE THREAD

**Issue by yangzj208** [atsamd-rs/atsamd#435]
请问有相关OTA的功能吗？
如果没有的话，能提供一个解决方案吗？都需要通过哪些步骤，尝试自己去实现下

**Comment by TDHolmes** [comment]
There is no OTA update function. This repo is only focused on peripheral support for ATSAMD MCUs, none of which have BT/WiFi on their own. They may or may not have features to support bootloaders, not sure about that

**Comment by bradleyharden** [comment]
@yangzj208, I'm going to close this. Please reopen of you have any additional questions.
