### ISSUE TITLE
USB freezing

### ISSUE THREAD

**Issue by Cightline** [atsamd-rs/atsamd#446]
Symptoms: When using `usbd-serial` the `lsusb` command on Linux will freeze temporarily when I restart or plug in my Feather M0. The freeze lasts about 10-20 seconds. 10% of the time when it unfreezes the Feather M0 does not appear in the `lsusb` output. I am using RTIC so I suspect it may be related. 

@ianrrees mentioned in chat that I could sniff the traffic with Wireshark. It may be a couple days before I can do that, so please standby.  

The [results](https://gist.githubusercontent.com/Cightline/3f59296e33e16c1082794dd992ee5232/raw/c520544b1894d88b63a4815ddfba0227a9fc5c30/j.log) of `sudo journal -f` after restarting the board. 

USB polling [function](https://gist.github.com/Cightline/7080a16dbb4d30bbdf705c69e423ee29)

**Comment by TDHolmes** [comment]
@Cightline any update on this one? Wondering if any changes since then might have fixed this

**Comment by TDHolmes** [comment]
This seems unlikely to be specific to our HAL code, and since we haven't heard an update, closing

**Comment by ianrrees** [comment]
This looks similar - I intend to dig in to soon: https://github.com/mvirkkunen/usb-device/issues/84

**Comment by ianrrees** [comment]
Aha!  @Cightline if you've got a minute, could you test with this modification to the HAL?  https://github.com/atsamd-rs/atsamd/pull/579

**Comment by Cightline** [comment]
I'll have time this weekend, been busy.
