### ISSUE TITLE
Should we run tests against multiple rust versions?

### ISSUE THREAD

**Issue by LongLiveCHIEF** [atsamd-rs/atsamd#484]

**Comment by TDHolmes** [comment]
I personally don't mind only building against nightly. Having more strict MSRV can make it harder to contribute and maintain

**Comment by jbeaurivage** [comment]
As this project seems to be focused on moving forward more than backwards compatibility, I would say testing against the latest stable+nightly rustc would be sufficient.

**Comment by TDHolmes** [comment]
@LongLiveCHIEF since you liked the above message, I'm gonna close this. If you think we should do something more, we can reopen
