### ISSUE TITLE
sleeping_timer_rtc examples don't work

### ISSUE THREAD

**Issue by TDHolmes** [atsamd-rs/atsamd#488]
According to git bisect, the culprit is a783ba9248f3130baf38c910b8ab1ebb6bbd66e2. Will work on fixing this

**Comment by TDHolmes** [comment]
ping @henrikssn since it's your commit, but I'll be taking a look at how to fix soon so don't feel obligated to investigate if you don't have the time

**Comment by ryankurte** [comment]
hey @TDHolmes what did you test this with? i've been trying to get the RTC running with RTIC on an m4 and am have having no luck today

**Comment by TDHolmes** [comment]
Hmm, shoot I thought I had tested the RTIC tests too. I'm mostly using `feather_m0` and looking at `sleeping_timer_rtc`

**Comment by TDHolmes** [comment]
@ryankurte I played around with this a bit today and couldn't figure it out. Can you create a new issue tracking this regression? I'm confused how me changing the implementation of the embedded-hal timer traits affected rtic-monotonic, because as far as I can tell they don't seem linked.
