### ISSUE TITLE
Add PTC peripheral

### ISSUE THREAD

**Issue by leo60228** [atsamd-rs/atsamd#502]
This allows for capacitive touch sensing. All official documentation is for the proprietary QTouch library, but [Adafruit_FreeTouch](https://github.com/adafruit/Adafruit_FreeTouch) is an MIT-licensed reimplementation of the core functionality for SAMD21.
I'm looking into implementing this myself.

**Comment by jbeaurivage** [comment]
Hi @leo60228, I'll invite you to go check out #420, which is an ongoing effort to implement PTC functionality. You're welcome to contribute to that PR to avoid duplicating efforts.

**Comment by leo60228** [comment]
Oh, I searched for an existing issue but I didn't check for a PR. I'll look at that (and test it on hardware).

**Comment by jbeaurivage** [comment]
Are you ok if I close this issue in that case?

**Comment by leo60228** [comment]
Sure.
