### ISSUE TITLE
Bring pygamer up to tier one status

### ISSUE THREAD

**Issue by TDHolmes** [atsamd-rs/atsamd#513]
It was a planned tier one board and is labeled as such, but conversion isn't complete.

**Comment by ianrrees** [comment]
I've got a pygamer on the way, hoping to dig in to this early December

**Comment by jbeaurivage** [comment]
Looks like it's not been obsoleted by Adafruit. I have no problem bringing it up to T1 because of its peripheral set. I think 6 T1 boards is probably enough, I prefer to keep the T1 list short and sweet, as not to overburden ourselves with every breaking change.
