### ISSUE TITLE
Clarify documentation of UART

### ISSUE THREAD

**Issue by uzytkownik** [atsamd-rs/atsamd#527]
I'm trying to use `sercom::v2` but it hangs during enabling of `SERCOM` due to `SYNCBUSY` being high. I suspect that I did not configured clocks correctly as it just specify to configure them in documentation.

It would be nice if documentation/examples was improved to show how the clocks should be configured.

**Comment by bradleyharden** [comment]
@uzytkownik, it sounds like #528 is the real problem. Can we close this issue?
