### ISSUE TITLE
Consider running clippy more aggressively

### ISSUE THREAD

**Issue by TDHolmes** [atsamd-rs/atsamd#574]
After #569, it would be good to run clippy more aggressively in CI. We currently run it but don't block anything on the result. I think it makes sense to deny errors everywhere and deny warnings in the HAL and tier one BSPs

**Comment by bradleyharden** [comment]
What is needed to implement this? Do I still owe some clippy fixes? I think so

**Comment by TDHolmes** [comment]
I recall there still being some missing safety comments on unsafe pieces of the SPI module
