### ISSUE TITLE
SERCOM0 samd51g19a - Using PA06 for RX in UART results in a Frame Error when reading

### ISSUE THREAD

**Issue by Josfemova** [atsamd-rs/atsamd#581]
The configuration used:

```Rust
pub fn uart0(
    clocks: &mut GenericClockController,
    baud: impl Into<Hertz>,
    sercom0: pac::SERCOM0,
    mclk: &mut pac::MCLK,
    uart_rx: impl Into<Pin<PA06, AlternateD>>,
    uart_tx: impl Into<Pin<PA04, AlternateD>>,
) -> Uart0 {
    let gclk0 = clocks.gclk0();
    let clock = &clocks.sercom0_core(&gclk0).unwrap();
    let baud = baud.into();
    let pads = uart::Pads::default().rx(uart_rx.into()).tx(uart_tx.into());
    uart::Config::new(mclk, sercom0, pads, clock.freq())
        .baud(baud, BaudMode::Fractional(Oversampling::Bits16))
        .enable()
}
```
- With `RXC` and `TXC` interrupts enabled 
- Writing works, error is only triggered when trying to read 
- Hardware is and Itsybitsy m4. Tested on two different boards
- Pin does work as a ADC0 input

Using `Pin<PA05, AlternateD>` works.
Tested with PA07 as RX and it seemed funky too, but I didn't look deeper into it. Will take my debug probe later and confirm if this also causes a frame error or if it was just momentary funkyness.

**Comment by Josfemova** [comment]
Relevant data: 

![datasheet screenshot](https://i.imgur.com/QWo9Su3.png)

![registers in cortex debug](https://i.imgur.com/u889lFb.png)

**Comment by Josfemova** [comment]
After further testing, I was able to pinpoint that the issue is indeed related to the TXPO configuration.
I changed [pads_thumbv7em.rs](https://github.com/atsamd-rs/atsamd/blob/master/hal/src/sercom/v2/uart/pads_thumbv7em.rs#L66-L68) to set the TXPO value to 0:
```
impl Txpo for Pad0 {
    const TXPO: TXPO_A = TXPO_A::TXPO_0;
}
```
and it worked. 

I think this would imply that the hal should provide the possibility to configure TXPO with value 0 as a Valid config for operation with pins pad 0 as TX and pad 2 as RX. Valid configs for UART would be
- TXPO 0 - pad[0] as TX,  pad[1], pad[2] and pad[3]  can be RX 
- TXPO 2 - pad[0] as TX, only pad[1] can be RX
- TXPO 3 - pad[0] as TX, only pad[1] and pad[3] can be RX

USART is similar but as XCK is used:
- TXPO 0 - pad[0] as TX,  pad[2] and pad[3]  can be RX 
- TXPO 2 - not a valid config for synchronous operation
- TXPO 3 - pad[0] as TX, pad[3] can be RX

**Comment by bradleyharden** [comment]
@jbeaurivage, I presume you've seen this. What's the status here? I thought I saw a fix come through, but I haven't been paying close attention. Can we close?

**Comment by jbeaurivage** [comment]
@bradleyharden I'll admit this issue kind of got off my mind since we last talked. I believe @Josfemova had suggested a fix over on Matrix. I'll try to find some time to look at it soonish.

**Comment by Josfemova** [comment]
IIRC, the proposed solution (not by me tho') was to have a macro system similar to what is done for thumbv6m

**Comment by bradleyharden** [comment]
Here's the relevant [message](https://matrix.to/#/!JbgTnIGpDxEHkjzSep:gitter.im/$JnMKG82FD-hqz1DtnR1PSemSnKo3quFN0RvRYU6DszQ?via=matrix.org&via=gitter.im&via=snoot.club).

If someone could summarize the problem and proposed solution, I might be able to implement it. But I don't want to dig through the conversation to figure it out.

**Comment by Josfemova** [comment]
Problem: 
The hal assumes that TXPO reg can be set to 0x2 and that that will work with all valid pad combinations. That is not the case. A value of 0x2 only allows for UART operation with pad[0] as TX and pad[1] as RX, pad[2] and pad[3] can either be left unused or be configured as RTS and CTS respectively. Using either pad[2] or pad[3] as RX will not be considered an invalid config by the current implementation, but it 
should -> the important thing here being, the configuration is invalid not because pad[2] or pad[3] can't be used as RX, but because the TXPO reg value shouldn't be 0x2 for those configurations. An incorrect TXPO value will allow for writing without problems, but will trigger a frame error when trying to read. 

This should apply to all sercoms of the SAM D5x/E5x family. Perhaps I should change the title of the issue to reflect that. 

As to the possible solution path:
The correct Txpo value can be derived from the provided pads and the operation mode (uart or usart)  - and so a Trait Txpo that gives that value can be implemented for certain combinations of the Pads struct. 

UART:
- pad[0] as TX,  pad[1], pad[2] or pad[3]  as RX -> TXPO should be 0x0
- pad[0] as TX, only pad[1] can be RX , pad[2] unused or RTS, pad[3] unused or CTS-> TXPO should be 0x2
- pad[0] as TX, only pad[1] and pad[3] can be RX, pad[2] unused or RTS-> TXPO should be 0x3

USART:
- pad[0] as TX, pad[1] as XCK, pad[2] and pad[3] as RX -> TXPO should be 0x0
- pad[0] as TX, pad[1] as XCK, pad[2] unused or used as RTS, pad[3] as RX -> TXPO should be 0x3

When a group of pads has many valid TXPO values, the one with lower implied restrictions should be chosen, so for example:
UART - pad[0] TX, pad[1] RX, no RTS or CTS, has valid TXPO values 0x0, 0x2 and 0x3, but as 0x0 imposes less restrictions, it might be preferred.

**Comment by jbeaurivage** [comment]
@Josfemova, I believe #607 should fix the issues you've been having. Would you mind giving it a test and reporting whether this works for you or not?

**Comment by Josfemova** [comment]
@jbeaurivage it works :)

**Comment by jbeaurivage** [comment]
Great!
