### ISSUE TITLE
Support L Variant SAMD[2|A]1E Parts

### ISSUE THREAD

**Issue by kiranshila** [atsamd-rs/atsamd#582]
As far as I can tell - SAMD[2|A]1ExL parts are not supported by this crate - is that correct? Specifically, this is the variant with a pinout optimized for ADC/PWM usage. I am using PB02 and PB03 in a design, but am getting

```console
error[E0609]: no field `pb03` on type `atsamd_hal::gpio::v2::Pins`
  --> src/bsp.rs:10:1
   |
10 | / hal::bsp_pins!(
11 | |     // GPIO
12 | |     PA07 { name: rf1_stat_led },
13 | |     PA06 { name: rf2_stat_led },
...  |
43 | |     }, //ALTC_SERCOM0[3]
44 | | );
   | |_^ help: a field with a similar name exists: `pa03`
```

when trying to use `bsp_pins!` on a SAMD21E17L part. I'm not sure if this is as simple as expanding the features in https://github.com/atsamd-rs/atsamd/blob/master/hal/src/gpio/v2/pin.rs#L1124 or if there are more implications.

**Comment by kiranshila** [comment]
Here is the app note that talks about the differences

**Comment by kiranshila** [comment]
I'm working on a PR here #583

**Comment by sajattack** [comment]
I noticed these chips have separate SVDs in newer atpack files from https://packs.download.microchip.com/ , but whether we need to generate entire PACs, I am not sure.

**Comment by bradleyharden** [comment]
@sajattack, we could probably just diff the SVDs. Isn't that how we decided to get rid of the memory-specifier fields of the part number?

**Comment by TDHolmes** [comment]
I believe @kiranshila diffed them and there wasn't anything important. Is that right?

**Comment by TDHolmes** [comment]
Closing now that #583 merged
