### ISSUE TITLE
Wio Terminal: `ButtonController` doesn't report release events

### ISSUE THREAD

**Issue by yvt** [atsamd-rs/atsamd#620]
Once a button is pressed, `ButtonController` stops reporting events for that button as if it's stuck in the pressed state. This can be observed through the `buttons` example.

This issue seems to have been introduced by commit 34ad122ab.

**Comment by bradleyharden** [comment]
@yvt, unfortunately, [we didn't have anyone to test the upgrade to the v2 APIs](https://github.com/atsamd-rs/atsamd/pull/542#issuecomment-1000926843). Perhaps that means we shouldn't have made it a Tier 1 board to begin with. In any event, it would be great if you could fix the examples and push an update. None of the active maintainers have this hardware right now.
