### ISSUE TITLE
Read state of EIC pin

### ISSUE THREAD

**Issue by sakian** [atsamd-rs/atsamd#629]
It doesn't look like it's possible to read the state of an external interrupt pin after it's been moved into an EIC (e.g. `ExtInt0::new(pin)`). Would it make sense to implement the Embedded HAL `InputPin` trait for the EIC pin?

**Comment by bradleyharden** [comment]
Probably. I'm not that familiar with the EIC API (which varies by chip), but it sounds reasonable. You could make a PR for it.

Although, I have to say, the last time I looked at EIC, I remember thinking that the whole API could use an overhaul. But that's much bigger project.
