### ISSUE TITLE
Example for standalone usage?

### ISSUE THREAD

**Issue by alexanderkoller** [atsamd-rs/atsamd#631]
Hi, this may be a dumb question, but how do I use the crates defined in this repository in a standalone project? As far as I can tell, this isn't really documented anywhere.

I'd like to use the [arduino_nano33iot crate](https://crates.io/crates/arduino_nano33iot) to write programs for my Arduino. I assume that I can do this by simply declaring a dependency (after moving `blinky_basic.rs` into `src/main.rs`):

```
[package]
name = "blinky_basic"
version = "0.1.0"
edition = "2021"

[dependencies]
arduino_nano33iot = "0.7.0"

[[bin]]
name = "blinky_basic"
path = "src/main.rs"
```

But this gives me an error that I find difficult to interpret:

```
$ cargo build
   Compiling blinky_basic v0.1.0 (/Users/koller/Documents/workspace/rust-temperature)
   Compiling atsamd21g v0.11.0
   Compiling atsamd-hal v0.14.0
LLVM ERROR: Global variable '__INTERRUPTS' has an invalid section specifier '.vector_table.interrupts': mach-o section specifier requires a segment and section separated by a comma.
error: could not compile `atsamd21g`
warning: build failed, waiting for other jobs to finish...
```

Is this the correct way to use the crate? What can I do about this error message? If it is related to the warning in the README ("Make sure that you have a new enough version of the gcc toolchain; the one installable even on recent versions of Ubuntu can fail to correctly link the vector table"), what is a "new enough version"? I'm on MacOS and have "Apple clang version 14.0.0 (clang-1400.0.29.102)".

**Comment by bradleyharden** [comment]
When you say

> after moving `blinky_basic.rs` into `src/main.rs`

Are you using the entirety of the `arduino_nano33iot` crate and moving one file within it? Or are you creating a new Rust crate that contains only `Cargo.toml` and `main.rs`?

If you're trying to create a new project, you'll definitely need the `build.rs` script and the `memory.x` file.

I think you'll also need the `cortex-m-rt` dependency. But I'm less sure about that. It's been a while since I set up a new project.

A quick search led me to [this issue](https://github.com/stm32-rs/stm32-rs/issues/158) that might help. You can also check out the [cortex-m-quickstart](https://github.com/rust-embedded/cortex-m-quickstart) template. That should be able to get you started.

**Comment by alexanderkoller** [comment]
Hi Bradley, thank you for the quick response.

Yes, I had also copied `build.rs` and `memory.x`.

I agree that the issue to which you linked seems similar to mine. Unfortunately, there is no explanation in that issue how it eventually got solved. I tried adding the dependencies in the `Cargo.toml` from `cortex-m-quickstart`, but newer versions of these were already dependencies of `arduino_nano33iot`, and adding them didn't make a difference.

Given the mention of "mach-o", it seems plausible that `cargo` uses the wrong build target, but I still don't understand how to select the correct one.

It may be worth mentioning that I can do `cargo build --release --example blinky_basic` in [arduino_nano33iot](https://github.com/atsamd-rs/atsamd/tree/master/boards/arduino_nano33iot), and this builds a binary for the Arduino without any errors. But even if I copy the entire `Cargo.toml` from `arduino_nano33iot` to my project, I still get the same error message.

If you want to have a look at my exact setup, here it is: https://github.com/alexanderkoller/rust-temperature

I'd be grateful for any help.

**Comment by bradleyharden** [comment]
You're missing the `.cargo/config` file. That's what specifies the target.

**Comment by bradleyharden** [comment]
@alexanderkoller, I would generally recommend starting from the cortex-m template. If we don't already recommend that in the README, then we could add that.

**Comment by alexanderkoller** [comment]
Which README? The main atsamd readme seems to be targeted at library developers, not at end users who simply want to depend on the crate. I could put something in the nano33iot readme, but then people who want to use other boards won't see it.

Happy to refer to the cortex-m quickstart, but there are at least two risks if we do that: (a) the crate versions in cortex-m are older than those on which the current atsamd depends, (b) the nano33iot needs thumbv6m in its .cargo/config, whereas the cortex-m quickstart lists several options. I could write some text that explains how to change the cortex-m template to one for nano33iot if you like.

**Comment by alexanderkoller** [comment]
Also, all the `cortex-m` dependencies are redundant anyway, because they are already dependencies of `arduino_nano33iot`. A minimal `Cargo.toml` for a project that depends on `arduino_nano33iot` looks like this:

```
[package]
authors = ["Alexander Koller <akoller@gmail.com>"]
edition = "2021"
readme = "README.md"
name = "blinky_basic"
version = "0.1.0"

[dependencies]
panic-halt = "0.2.0"
arduino_nano33iot = "0.7.0"

[[bin]]
name = "blinky_basic"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
```

I would consider copy & pasting this example into the README directly, and then linking to the [build.rs](https://github.com/atsamd-rs/atsamd/blob/master/boards/arduino_nano33iot/build.rs), [memory.x](https://github.com/atsamd-rs/atsamd/blob/master/boards/arduino_nano33iot/memory.x), and [.cargo/config](https://github.com/atsamd-rs/atsamd/blob/master/boards/arduino_nano33iot/.cargo/config) of [arduino_nano33iot](https://github.com/atsamd-rs/atsamd/tree/master/boards/arduino_nano33iot). What do you think?
