### ISSUE TITLE
Non-working implementation of eic::pin::ExternalInterrupt::id()

### ISSUE THREAD

**Issue by johngigantic** [atsamd-rs/atsamd#640]
In attempting to use the button_debounce_pins() function in my RTIC example, I was unable to successfully use the atsamd_hal::thumbv7em::eic::pin::ExternalInterrupt trait. Instead of using the id() function, I simply hardcoded the ID's value in.

I've submitted a pull request #639 which has the edge_counter example. This has the hard-coded fix as well as the non-working line on lines 70/71, and I'm not sure how to get line 71 working in a more idiomatic way.

**Comment by johngigantic** [comment]
Duplicate issue of #628

**Comment by jbeaurivage** [comment]
Closed by #641
