### ISSUE TITLE
Unable to use cargo flash in the feather_m0 repo

### ISSUE THREAD

**Issue by nvsd** [atsamd-rs/atsamd#682]
**Describe the bug**
I'm trying to use cargo flash 
I'm unable to use cargo-flash, probe-run, and cargo-embed with the examples in the feather_m0 repo due to the below error while using a Jlink EDU Mini with a feather M0 proto
```
Caused by:
    0: Failed to erase flash sector at address 0x00000000.
    1: The execution of 'erase_sector' failed with code 1. This might indicate a problem with the flash algorithm.
```

I can flash the board using hf2 so the board works. I can also connect to the board using Jlink commander.
I assume I have a configuration issue, but I'm unsure. Let me know what else I can provide.

**Comment by nvsd** [comment]
Looks like its a probe-rs issue
https://github.com/probe-rs/probe-rs/issues/1599

**Comment by sajattack** [comment]
This currently only supports ATSAME51, but it sounds like you need something similar for atsamd21 if I understand correctly. https://github.com/atsamd-rs/atsamd-flash-algorithm
