### ISSUE TITLE
edgebadge: embedded-graphics 0.8.0+ compatibility

### ISSUE THREAD

**Issue by LuckyTurtleDev** [atsamd-rs/atsamd#724]
The edgebade does still stuck on embeded-graphics 0.7.0 because of the outdated st7735-lcd-rs crate.

see also: https://github.com/LuckyTurtleDev/pybadge-high/issues/11

**Comment by LuckyTurtleDev** [comment]
I currently do not have access to an edgebade for testing. Wwould it be ok to simple increase the st7735-lcd-rs  crate version and keep everything else the same?

**Comment by jbeaurivage** [comment]
Hey @LuckyTurtleDev, as I understand it, you want to bump the `embedded-graphics` dependency of `edgebadge`, correct?
You can open a PR with the appropriate version bumps, and we will review it.

**Comment by LuckyTurtleDev** [comment]
> Hey @LuckyTurtleDev, as I understand it, you want to bump the `embedded-graphics` dependency of `edgebadge`, correct? You can open a PR with the appropriate version bumps, and we will review it.

Yes, I planed it for today. But it looks like @orsinium was faster.
