### ISSUE TITLE
QSPI support

### ISSUE THREAD

**Issue by nic-hartley** [atsamd-rs/atsamd#93]
Some boards, e.g. the [ItsyBitsy M4](https://www.adafruit.com/product/3800), have a flash chip onboard which they use QSPI to communicate with. It'd be real nice to support those. I'll start work on those once I have a chance if no one else has, but that won't be for a while, so if someone else would like to implement it in the mean time, I'm happy to test on my board.

**Comment by sajattack** [comment]
I'll see what I can do.

**Comment by sajattack** [comment]
Started work here https://github.com/sajattack/atsamd/tree/qspi

**Comment by jacobrosenthal** [comment]
Looks like itsy has gd25, so does pygamer. Did you evaluate https://github.com/jonas-schievink/spi-memory at all?

**Comment by sajattack** [comment]
It's fat formatted so I've looked at https://github.com/thejpster/embedded-sdmmc-rs and the adafruit qspi lib.

**Comment by twitchyliquid64** [comment]
I'm also interested in this - lemme know if theres anything I can do to help.

**Comment by sajattack** [comment]
I've got the low-level interface done I think, next I'm planning to wrap it in embedded-sdmmc, I'm not sure if cataloging different flash chips the way adafruit does is within our purview.

**Comment by twitchyliquid64** [comment]
That `BlockDevice` trait looks awesome. The internal NVM is organized into 512 byte pages so we could actually support the same interface for reading/writing from the internal NVM.

**Comment by sajattack** [comment]
Yeah it looks great except it takes &self instead of &mut self for some reason.

**Comment by sajattack** [comment]
I'm in mutability mismatch hell

**Comment by sajattack** [comment]
Ok, got that sorted, now I'm trying to test and it's complaining the flash chip doesn't have an MBR lmao.

**Comment by twitchyliquid64** [comment]
Hmmmm can you use the interior mutability pattern and wrap it in a new type?

**Comment by sajattack** [comment]
I figured out the mutability problem, now I need to figure out how to write an MBR to a spi flash chip.

**Comment by sajattack** [comment]
So it turns out the partition is fat12 even though my OS was reporting fat16, and embedded-sdmmc doesn't support fat12. In addition, I was told the chips are too small to be reformatted as fat16.

**Comment by sajattack** [comment]
I also think this will have limited utility until we have our own USB filesystem driver, we could use adafruit's but that ties us to their locked down MBR and such.

**Comment by sajattack** [comment]
Should I put up what I have minus the embedded-sdmmc? I think you can write arbitrary bytes to storage and retrieve them.

**Comment by twitchy-jsonp** [comment]
Please do!

I'll be doing a bunch of flying in the next few days, so i might have some time to look into a sneaky USB mass storage device class.

**Comment by twitchyliquid64** [comment]
Please do!

I'll be doing a bunch of flying in the next few days, so i might have some time to look into a sneaky USB mass storage device class.

**Comment by marcushill** [comment]
Has there been any progress on this? I saw it was started, but not merged in #103. I rebased that on master and it seems to work for me on the feather m4 express (at least trivially), but I'd really love to have that in the released crate. Thanks in advance!

**Comment by sajattack** [comment]
Thanks for testing, I'll clean up that PR a bit and merge it when it's ready.

**Comment by sajattack** [comment]
@marcushill I tried to use this with a more substantial example in #93 and it doesn't seem to work for me. What made you think it was working?

**Comment by jessebraham** [comment]
QSPI support was added in #297 (not sure on the level of completeness, but is usable) for `thumbv7em` targets, and the `thumbv6m` targets don't seem to have this peripheral. Is there any reason this can't be closed?
